version: "2"
services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    volumes:
      - ".:/var/www/opensmarthome"

  database:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: topsecret
      MYSQL_DATABASE: opensmarthome
      MYSQL_USER: osh_user
      MYSQL_PASSWORD: osh_password

  proxy:
    build:
      context: docker/traefik
    ports:
      - 8080:8080
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  broker:
    image: rabbitmq:3-management
    hostname: broker