old_sound_rabbit_mq:
    connections:
        default:
            host:     '127.0.0.1'
            port:     5672
            user:     'guest'
            password: 'guest'
            vhost:    '/'
            lazy:     false
            connection_timeout: 1
            read_write_timeout: 1
